"""empty message

Revision ID: 2f50eee237ef
Revises: 93a4a45c3b1b
Create Date: 2021-11-29 11:32:01.760405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f50eee237ef'
down_revision = '93a4a45c3b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_data', table_name='video')
    op.drop_column('video', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('data', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_video_data', 'video', ['data'], unique=False)
    # ### end Alembic commands ###
