"""empty message

Revision ID: 320166363fd8
Revises: d3c13999cbea
Create Date: 2021-11-08 12:24:43.499595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320166363fd8'
down_revision = 'd3c13999cbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_dijk', table_name='test')
    op.drop_index('ix_test_title', table_name='test')
    op.drop_table('test')
    op.add_column('video', sa.Column('data', sa.String(length=120), nullable=True))
    op.drop_index('ix_video_cords', table_name='video')
    op.create_index(op.f('ix_video_data'), 'video', ['data'], unique=False)
    op.drop_column('video', 'cords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('cords', sa.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_video_data'), table_name='video')
    op.create_index('ix_video_cords', 'video', ['cords'], unique=False)
    op.drop_column('video', 'data')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dijk', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_title', 'test', ['title'], unique=False)
    op.create_index('ix_test_dijk', 'test', ['dijk'], unique=False)
    # ### end Alembic commands ###
