"""videos table

Revision ID: 3a7f213b8d3f
Revises: f6ca42c74a23
Create Date: 2021-10-25 15:17:33.442158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7f213b8d3f'
down_revision = 'f6ca42c74a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_beschrijving', table_name='video')
    op.create_index(op.f('ix_video_beschrijving'), 'video', ['beschrijving'], unique=False)
    op.drop_index('ix_video_cords', table_name='video')
    op.create_index(op.f('ix_video_cords'), 'video', ['cords'], unique=False)
    op.drop_index('ix_video_title', table_name='video')
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.create_index('ix_video_title', 'video', ['title'], unique=False)
    op.drop_index(op.f('ix_video_cords'), table_name='video')
    op.create_index('ix_video_cords', 'video', ['cords'], unique=False)
    op.drop_index(op.f('ix_video_beschrijving'), table_name='video')
    op.create_index('ix_video_beschrijving', 'video', ['beschrijving'], unique=False)
    # ### end Alembic commands ###
