"""Test table

Revision ID: 498172dc0e3c
Revises: 3a7f213b8d3f
Create Date: 2021-10-25 15:23:37.285170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498172dc0e3c'
down_revision = '3a7f213b8d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_title'), 'test', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_title'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
