"""empty message

Revision ID: 5ff575fd8728
Revises: 04101e354d37
Create Date: 2021-11-08 12:48:51.551214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff575fd8728'
down_revision = '04101e354d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_data', table_name='video')
    op.drop_column('video', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('data', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_video_data', 'video', ['data'], unique=False)
    # ### end Alembic commands ###
