"""empty message

Revision ID: 73ffc5767b09
Revises: be9d7c83f301
Create Date: 2021-11-29 11:38:20.923050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ffc5767b09'
down_revision = 'be9d7c83f301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten', sa.String(length=500), server_default='[{"time":0,"laserOnOff":"begin"}]', nullable=True))
    op.add_column('video', sa.Column('data', sa.String(length=120), nullable=True))
    op.drop_index('ix_video_data1', table_name='video')
    op.drop_index('ix_video_videoPunten1', table_name='video')
    op.create_index(op.f('ix_video_data'), 'video', ['data'], unique=False)
    op.create_index(op.f('ix_video_videoPunten'), 'video', ['videoPunten'], unique=False)
    op.drop_column('video', 'data1')
    op.drop_column('video', 'videoPunten1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten1', sa.VARCHAR(length=500), server_default=sa.text('\'[{"time"NULL,"laserOnOff":"begin"}]\''), nullable=True))
    op.add_column('video', sa.Column('data1', sa.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_video_videoPunten'), table_name='video')
    op.drop_index(op.f('ix_video_data'), table_name='video')
    op.create_index('ix_video_videoPunten1', 'video', ['videoPunten1'], unique=False)
    op.create_index('ix_video_data1', 'video', ['data1'], unique=False)
    op.drop_column('video', 'data')
    op.drop_column('video', 'videoPunten')
    # ### end Alembic commands ###
