"""empty message

Revision ID: 88290f47550f
Revises: 320166363fd8
Create Date: 2021-11-08 12:39:48.245898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88290f47550f'
down_revision = '320166363fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_video_videoPunten'), 'video', ['videoPunten'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_videoPunten'), table_name='video')
    op.drop_column('video', 'videoPunten')
    # ### end Alembic commands ###
