"""empty message

Revision ID: 93a4a45c3b1b
Revises: aa35264d5abe
Create Date: 2021-11-08 13:21:30.412429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a4a45c3b1b'
down_revision = 'aa35264d5abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('data', sa.String(length=120), nullable=True))
    op.add_column('video', sa.Column('videoPunten', sa.String(length=500), server_default="[{'time' : 0}]", nullable=True))
    op.drop_index('ix_video_videoPunten1', table_name='video')
    op.create_index(op.f('ix_video_data'), 'video', ['data'], unique=False)
    op.create_index(op.f('ix_video_videoPunten'), 'video', ['videoPunten'], unique=False)
    op.drop_column('video', 'videoPunten1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten1', sa.VARCHAR(length=500), server_default=sa.text("'test'"), nullable=True))
    op.drop_index(op.f('ix_video_videoPunten'), table_name='video')
    op.drop_index(op.f('ix_video_data'), table_name='video')
    op.create_index('ix_video_videoPunten1', 'video', ['videoPunten1'], unique=False)
    op.drop_column('video', 'videoPunten')
    op.drop_column('video', 'data')
    # ### end Alembic commands ###
