"""empty message

Revision ID: aa35264d5abe
Revises: 5ff575fd8728
Create Date: 2021-11-08 12:51:19.419444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa35264d5abe'
down_revision = '5ff575fd8728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten1', sa.String(length=500), server_default='test', nullable=True))
    op.drop_index('ix_video_videoPunten', table_name='video')
    op.create_index(op.f('ix_video_videoPunten1'), 'video', ['videoPunten1'], unique=False)
    op.drop_column('video', 'videoPunten')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('videoPunten', sa.VARCHAR(length=500), nullable=True))
    op.drop_index(op.f('ix_video_videoPunten1'), table_name='video')
    op.create_index('ix_video_videoPunten', 'video', ['videoPunten'], unique=False)
    op.drop_column('video', 'videoPunten1')
    # ### end Alembic commands ###
