"""videos table

Revision ID: f6ca42c74a23
Revises: 46770b7be52f
Create Date: 2021-10-25 13:09:53.742016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ca42c74a23'
down_revision = '46770b7be52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('cords', sa.String(length=120), nullable=True))
    op.add_column('video', sa.Column('href', sa.String(length=120), nullable=True))
    op.drop_index('ix_video_putne', table_name='video')
    op.create_index(op.f('ix_video_cords'), 'video', ['cords'], unique=True)
    op.create_index(op.f('ix_video_href'), 'video', ['href'], unique=False)
    op.drop_column('video', 'putne')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('putne', sa.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_video_href'), table_name='video')
    op.drop_index(op.f('ix_video_cords'), table_name='video')
    op.create_index('ix_video_putne', 'video', ['putne'], unique=False)
    op.drop_column('video', 'href')
    op.drop_column('video', 'cords')
    # ### end Alembic commands ###
